# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-releases:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet run --project mcLaunch.Build/ .
    - name: Upload win-x64 artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mcLaunch-win-x64.zip
        path: output/releases/mcLaunch-win-x64.zip
    - name: Upload win-arm64 artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mcLaunch-win-arm64.zip
        path: output/releases/mcLaunch-win-arm64.zip
    - name: Upload linux-x64 artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mcLaunch-linux-x64.zip
        path: output/releases/mcLaunch-linux-x64.zip
    - name: Upload linux-arm64 artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mcLaunch-linux-arm64.zip
        path: output/releases/mcLaunch-linux-arm64.zip
  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Run mcLaunch.Build
      run: dotnet run --project mcLaunch.Build/ . --macos
    - name: Upload macOS x64 bundle
      uses: actions/upload-artifact@v4
      with:
        name: mcLaunch-macOS-x64.zip
        path: output/releases/mcLaunch-osx-x64.zip
    - name: Upload macOS arm64 bundle
      uses: actions/upload-artifact@v4
      with:
        name: mcLaunch-macOS-arm64.zip
        path: output/releases/mcLaunch-osx-arm64.zip
